name: 🐛 Bug
description: Report an issue to help improve the project.
title: "bug: <description>"
labels: ["bug", "hacktoberfest"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description:
        Write a brief description of the question or issue, also include what you tried and what didn't work. *Please add screenshots if applicable along with* ***steps to reproduce the issue and reference links (if applicable)***. If you need help or if you want to to discuss something with us, join the WalkingPal [Discord community](https://discord.gg/Et3aQTsW6a)!

        You can assign this issue to yourself if you want to work on it.
    validations:
      required: true
